import os
from controllers.base_controller import Controller
from controllers.command_thread import CommandThread
from loguru import logger as l

TOOL_DISPLAY_NAME = "Nikto"
TOOL_NAME = "nikto"
TEMP_FILE_NAME = "tmp/nikto-temp.txt"

# Interface options
scan_options = [
    ("Tuning", "text", "-Tuning", "Scan tuning (e.g. 1,2,3)"),
    ("Display", "text", "-Display", "Display options (e.g. 1,2,V)"),
]

class NiktoController(Controller):
    def __init__(self):
        # Initialization identical to Nmap
        super().__init__(TOOL_DISPLAY_NAME, TEMP_FILE_NAME, TOOL_NAME)

    def __build_command__(self, target: str, options: dict) -> list:
        # Building command as a list
        command = ["nikto", "-h", target, "-o", TEMP_FILE_NAME, "-Format", "txt"]
        
        # Adding dynamic options
        for option_key, value in options.items():
            if value:
                command.append(option_key)
                command.append(str(value))
        return command

    def __run_command__(self, command):
        # Implementation identical to Nmap to properly handle the thread
        class NiktoCommandThread(CommandThread):
            def run(self):
                super().run()
                if self._stop_event.is_set():
                    self.calling_controller.__remove_temp_file__()

        return NiktoCommandThread(command, self)

    def __parse_temp_results_file__(self):
        """
        Reads the file generated by Nikto and returns it as a string
        to be displayed in the <pre> tag of your view.
        """
        try:
            if os.path.exists(TEMP_FILE_NAME):
                with open(TEMP_FILE_NAME, "r") as file:
                    results = file.read()
                return results, None
            else:
                return "No results found.", None
        except Exception as e:
            l.error(f"Error parsing Nikto: {e}")
            return None, e
