import os
import requests
import json
from loguru import logger as l

# Static Fallback (Used ONLY if the internet is down or API fails)
TOOL_TO_MITRE_FALLBACK = {
    # Reconnaissance
    "nmap": "T1046",
    "nmap_scan": "T1046",
    "dig": "T1590",
    "theharvester": "T1593",
    "the_harvester": "T1593",
    "feroxbuster": "T1083",
    "nikto": "T1595",
    "dirsearch": "T1083",

    # Weaponization
    "w4af": "T1595.002",
    "w4af_audit": "T1595.002",
    "nmap-vuln": "T1595.002",
    "nmap_vuln": "T1595.002",
    "nmap_vuln_scan": "T1595.002",
    "wpscan": "T1595.002",

    # Delivery
    "smtp-email-spoofer-py": "T1566",
    "smtp_email_spoofer": "T1566",

    # Exploitation
    "sqlmap": "T1190",
    "commix": "T1059"
}

def get_technique_dynamically(tool_name, scan_results=None):
    """
    Analyzes tool results using AI to determine the MITRE ATT&CK technique.
    If the AI fails or results are missing, it falls back to a static mapping.
    """
    clean_name = tool_name.lower().strip()
    
    # Google Gemini API Key
    api_key = os.getenv("GEMINI_API_KEY") 
    
    if not api_key:
        l.error("Environment ERROR: GEMINI_API_KEY variable not found!")

    if not api_key or not scan_results or len(str(scan_results).strip()) < 10:
        l.warning(f"Insufficient data or missing API key. Using fallback for {clean_name}.")
        return TOOL_TO_MITRE_FALLBACK.get(clean_name, None)

    raw_text = str(scan_results).lower()

    try:
        l.info(f"Sending {clean_name} logs to Artificial Intelligence...")

        # Direct URL to Google AI API (Bypassing SDK bugs)
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
        headers = {'Content-Type': 'application/json'}
        
        # AI Analysis Prompt
        prompt = f"""
        You are an expert Cyber Threat Intelligence analyst.
        Analyze the following security scan log generated by the tool '{tool_name}'.
        Determine the SINGLE MOST ACCURATE Enterprise MITRE ATT&CK technique ID (e.g., T1046, T1595.002, T1190, T1083) that describes the behavior in the log.
        Respond ONLY with the technique ID. No markdown, no explanations.
        
        --- LOG EXCERPT ---
        {raw_text[:2000]}
        """

        # Request body formatting
        data = {
            "contents": [{
                "parts": [{"text": prompt}]
            }],
            "generationConfig": {
                "temperature": 0.1 # Low temperature for precise, non-creative results
            }
        }

        # Executing the POST request
        response = requests.post(url, headers=headers, json=data)
        
        # Response parsing
        if response.status_code == 200:
            result_json = response.json()
            # Extracting the text from the Google JSON response
            ai_id = result_json['candidates'][0]['content']['parts'][0]['text'].strip().replace("`", "")
            
            if ai_id.startswith("T"):
                l.success(f"AI analyzed the logs and decided: {ai_id}")
                return ai_id
            else:
                l.error(f"AI returned an invalid format: {ai_id}")
        else:
            l.error(f"Google API Server Error: {response.status_code} - {response.text}")

    except Exception as e:
        l.error(f"Critical AI communication error: {e}")

    # Final fallback if API call fails entirely
    l.warning(f"Falling back to static dictionary for {clean_name}")
    return TOOL_TO_MITRE_FALLBACK.get(clean_name, None)
